Ignore unset CPAN metadata fields
Otherwise this can happen:

    $ fpm -t deb -s cpan --verbose 'Lingua::JA::Romanize::Japanese'
    Asking metacpan about a module {:module=>"Lingua::JA::Romanize::Japanese", :level=>:info}
    Downloading perl module {:distribution=>"Lingua-JA-Romanize-Japanese", :version=>nil, :level=>:info}
    Setting package name from 'name' {:name=>"Lingua-JA-Romanize-Japanese", :level=>:info}
    /usr/lib/ruby/gems/1.9.1/gems/fpm-1.1.0/lib/fpm/package/cpan.rb:86:in `input': undefined method `join' for nil:NilClass (NoMethodError)
	    from /usr/lib/ruby/gems/1.9.1/gems/fpm-1.1.0/lib/fpm/command.rb:299:in `block in execute'
	    from /usr/lib/ruby/gems/1.9.1/gems/fpm-1.1.0/lib/fpm/command.rb:298:in `each'
	    from /usr/lib/ruby/gems/1.9.1/gems/fpm-1.1.0/lib/fpm/command.rb:298:in `execute'
	    from /usr/lib/ruby/gems/1.9.1/gems/clamp-0.6.3/lib/clamp/command.rb:67:in `run'
	    from /usr/lib/ruby/gems/1.9.1/gems/fpm-1.1.0/lib/fpm/command.rb:449:in `run'
	    from /usr/lib/ruby/gems/1.9.1/gems/clamp-0.6.3/lib/clamp/command.rb:125:in `run'
	    from /usr/lib/ruby/gems/1.9.1/gems/fpm-1.1.0/bin/fpm:8:in `<top (required)>'
	    from /usr/bin/fpm:23:in `load'
	    from /usr/bin/fpm:23:in `<main>'