Upgrade from distribute to setuptools
Projects have now merged: https://pypi.python.org/pypi/distribute/0.7.3.

Fixes:

    Building wheels for collected packages: distribute {:level=>:info}
      Running setup.py bdist_wheel for distribute: started {:level=>:info}
      Running setup.py bdist_wheel for distribute: finished with status 'error' {:level=>:info}
      Complete output from command /.../package-virtualenv-build-.../usr/share/python/.../bin/python -u -c "import setuptools, tokenize;__file__='/workspace/build-jessie/pip-build-o5vB2p/distribute/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /workspace/build-jessie/tmp9ETJLOpip-wheel- --python-tag cp27: {:level=>:info}
      Traceback (most recent call last): {:level=>:info}
        File "<string>", line 1, in <module> {:level=>:info}
        File "/workspace/build-jessie/pip-build-o5vB2p/distribute/setup.py", line 58, in <module> {:level=>:info}
          setuptools.setup(**setup_params) {:level=>:info}
      Failed building wheel for distribute {:level=>:info}
        File "/usr/lib/python2.7/distutils/core.py", line 137, in setup {:level=>:info}
          ok = dist.parse_command_line() {:level=>:info}
        File "setuptools/dist.py", line 276, in parse_command_line {:level=>:info}
          result = _Distribution.parse_command_line(self) {:level=>:info}
        File "/usr/lib/python2.7/distutils/dist.py", line 467, in parse_command_line {:level=>:info}
          args = self._parse_command_opts(parser, args) {:level=>:info}
        File "setuptools/dist.py", line 602, in _parse_command_opts {:level=>:info}
          nargs = _Distribution._parse_command_opts(self, parser, args) {:level=>:info}
        File "/usr/lib/python2.7/distutils/dist.py", line 523, in _parse_command_opts {:level=>:info}
          cmd_class = self.get_command_class(command) {:level=>:info}
        File "setuptools/dist.py", line 406, in get_command_class {:level=>:info}
          ep.require(installer=self.fetch_build_egg) {:level=>:info}
        File "pkg_resources.py", line 2254, in require {:level=>:info}
          working_set.resolve(self.dist.requires(self.extras),env,installer))) {:level=>:info}
        File "pkg_resources.py", line 2471, in requires {:level=>:info}
          dm = self._dep_map {:level=>:info}
        File "pkg_resources.py", line 2682, in _dep_map {:level=>:info}
          self.__dep_map = self._compute_dependencies() {:level=>:info}
        File "pkg_resources.py", line 2699, in _compute_dependencies {:level=>:info}
          from _markerlib import compile as compile_marker {:level=>:info}
      ImportError: No module named _markerlib {:level=>:info}
       {:level=>:info}
      ---------------------------------------- {:level=>:info}
      Running setup.py clean for distribute {:level=>:info}